version: "3.9"

services:
  postgres:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DATABASE
    ports:
      - target: 27017
        published: $MONGO_PORT
    volumes:
      - ./mongo_initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:6.2
    ports:
      - target: 6379
        published: $REDIS_PORT

  rabbitmq:
    image: rabbitmq:3.9-management
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_USERNAME
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASSWORD
    ports:
      - target: 5672
        published: $RABBITMQ_PORT
      - target: 15672
        published: 15672
